# Generated by Django 6.0.3 on 2026-10-05 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('target_role', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CleanupRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ran_at', models.DateTimeField(auto_now_add=True)),
                ('total_deleted', models.PositiveIntegerField(default=0)),
                ('detail', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='IgnoredDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown Board', max_length=255)),
                ('url', models.URLField(unique=True)),
                ('country', models.CharField(default='Zimbabwe', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MailCleanupTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv_career', models.CharField(max_length=255)),
                ('job_title', models.CharField(blank=True, default='N/A', max_length=255)),
                ('job_url', models.URLField()),
                ('email_link', models.EmailField(max_length=254)),
                ('job_type', models.CharField(blank=True, default='Remote/Full-time', max_length=100)),
                ('country', models.CharField(default='Zimbabwe', max_length=100)),
                ('found_at', models.DateTimeField(auto_now_add=True)),
                ('applied', models.BooleanField(default=False)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('cv_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_leads', to='scrapping_engine.candidatecv')),
                ('job_board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_leads', to='scrapping_engine.jobboard')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILURE', 'Failure')], max_length=10)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_logs', to='scrapping_engine.joblead')),
            ],
        ),
        migrations.AddIndex(
            model_name='joblead',
            index=models.Index(fields=['applied'], name='scrapping_e_applied_934c7c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='joblead',
            unique_together={('job_url', 'email_link')},
        ),
    ]
